project:
  type: website
execute:
  browser: true
  
website:
  title: "ISSS608 - Visual Analytics"
  page-navigation: true
  navbar:
    background: white
    foreground: black
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - text: Hands-on Exercise
        menu:
          - text: Exercise01
            href: Hands-on_Exercise/Hands-on_Ex01/Hands-on_Ex01.qmd
          - text: Exercise02
            href: Hands-on_Exercise/Hands-on_Ex02/Hands-on_Ex02.qmd
          - text: Exercise03
            href: Hands-on_Exercise/Hands-on_Ex03/Hands-on_Ex03.qmd
      - text: In-class Exercise
        menu:
          - in-class/ex1.qmd
      - text: Take-home Exercise
        menu:
          - text: Take-Home Ex01
            href: Take-home_Exercise/Take-home_Ex01/Take-home_Ex01.qmd

  page-footer:
    center: "© 2025 Lucas Luo ｜ SMU ISSS608"
    background: white
    foreground: "#888888"
format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc-location: right
    fontsize: 1.05em
    smooth-scroll: true

editor: visual

