---
title: "ISSS608 - Visual Analytics"
format:
  html:
    page-layout: full
    toc: false
---

<div style="text-align:center; padding-top: 2rem; padding-bottom: 2rem;">
  <h1 style="font-weight:500; font-size:2.5rem; margin-bottom:0.2em;">Welcome to ISSS608</h1>
  <p style="font-size:1.2rem; color:#555;">
    A Visual Analytics Journey through Data, Design, and Discovery
  </p>
</div>

---

### ✦ Hands-on Exercises

- [Exercise 1](Hands-on_Exercise/Hands-on_Ex01/Hands-on_Ex01.qmd)
- [Exercise 2](Hands-on_Exercise/Hands-on_Ex02/Hands-on_Ex02.qmd)
- [Exercise 3](Hands-on_Exercise/Hands-on_Ex03/Hands-on_Ex03.qmd)
- [Exercise 4](Hands-on_Exercise/Hands-on_Ex04/Hands-on_Ex04.qmd)
- [Exercise 5](Hands-on_Exercise/Hands-on_Ex05/Hands-on_Ex05.qmd)
- [Exercise 6](Hands-on_Exercise/Hands-on_Ex06/Hands-on_Ex06.qmd)

### ✦ In-class Exercises

- [In-class 5](In-class_Exercise/In-class_Ex05/In-class_Ex05.qmd)

### ✦ Take-home Exercises

- [Take-home 1](Take-home_Exercise/Take-home_Ex01/Take-home_Ex01.qmd)
- [Take-home 1](Take-home_Exercise/Take-home_Ex01/Take-home_Ex01-phaseII.qmd)
- [Take-home 2](Take-home_Exercise/Take-home_Ex02/Take-home_Ex02.qmd)
---

<div style="text-align:center; margin-top: 4rem; font-size: 0.95rem; color: #999;">
  © 2025 Lucas Luo · Singapore Management University
</div>
